name: CI & Docker Build

on:
  push:
    branches: [ "**" ]      
  pull_request:

jobs:
  test:
    name: Run Go tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./... -v

  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: test  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t price-scraper .
